### ISSUE TITLE
Tracking issue for adding a question

### ISSUE THREAD

**Issue by asensio-project** [asensio-project/trivial_packager#2]
This is the tracking issue for let the users add questions:

- [x] Add support for adding questions in the backend
- [x] Add support for adding questions in the frontend
- [x] Adapt the form for guests or teachers with JS
- [x] Alert the user before discard a question
- [x] Support for sliding the form
- [x] Connect the frontend with the backend
- [x] Download the images of the questions
- [x] Show question preview
- [x] #3

**Comment by asensio-project** [comment]
Done!
